language: go

go:
- '1.11'

notifications:
  email: false

env:
- GO111MODULE=on

git:
  depth: 1

os: linux

install:
- go get golang.org/x/tools/cmd/goimports
- go mod vendor

script:
- diff <(goimports -d $(find . -type f -name '*.go' -not -path "*/vendor/*")) <(printf "")
- go test -v -mod=vendor ./...

